# Example Playbok to configure PPSM
- name: Configure PPDM
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)    
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm_setup_password  set !"
    when: (ppdm_setup_password is not defined) or (ppdm_setup_password|length == 0)      
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"  
  - name: Check Appliance Ready https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role:
      name: check_api_ready       
