# Example Playbok to deploy agents
- name: Deploy App Agent
  hosts: windows
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  vars:
   agent_ver: "1915"
   agent_branch: "19.15-69"  
   agent_src: /tmp
  tasks:
  - name: Checking Required Variable ppdm_fqdn
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)   
  - name: Copy agent to {{ ansible_fqdn }}
    ansible.windows.win_copy:
      src: "{{ agent_src }}/{{ app_agent }}"
      dest: C:/Temp
  - name: Unzip Agents
    community.windows.win_unzip:
      src: "C:/Temp/{{ app_agent | basename }}"
      dest: C:/swdist
  - name: "Install {{ app_agent | basename }} on {{ ansible_fqdn }}"
    ansible.windows.win_package:
    path: "C:/swdist/nt64/{{ app_agent | basename | splitext | first }}.exe"
    product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}'
    arguments:
    - /s
    - PPDMHostName={{ ppdm_fqdn }}
    - EnableFirewallRules=1
    - PreferredAddress={{ ansible_fqdn }}
