# Example Playbok to deploy agents
- name: Deploy App Agent
  hosts: windows
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  vars:
   agent_ver: "1915"
   agent_branch: "19.15-69"  
   agent_src: /tmp
  tasks:
  - name: Checking Required Variable ppdm_fqdn
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)   
  - name: Copy agent to {{ ansible_fqdn }}
    ansible.windows.win_copy:
      src: "{{ agent_src }}/{{ app_agent }}"
      dest: C:/Temp
  - name: Unzip Agents
    community.windows.win_unzip:
      src: "C:/Temp/{{ app_agent | basename }}"
      dest: C:/swdist
    register: unzip  
  - name: Find files in path based on regex pattern
    ansible.windows.win_find:
      paths: c:/swdist/ntx64
      patterns: "*.exe"
    register: find_file        
  - name: "Install {{ find_file.files[0].path }} on {{ ansible_fqdn }}"
    ansible.windows.win_package:
      path: "{{ find_file.files[0].path }}"
      product_id: "{{ app_agent_product_id }}"
      arguments:
      - /s
      - PPDMHostName={{ ppdm_fqdn }}
      - EnableFirewallRules=1
      - PreferredAddress={{ ansible_fqdn }}
    when: app_agent == fs_agent_windows
  - name: "Install {{ find_file.files[0].path }} on {{ ansible_fqdn }}"
    ansible.windows.win_package:
      path: "{{ find_file.files[0].path }}"
      product_id: "{{ app_agent_product_id }}"
      arguments:
      - /s
      - PPDMHostName={{ ppdm_fqdn }}
      - EnableFirewallRules=1
      - PreferredAddress={{ ansible_fqdn }}
      - EnableSSMS= {{ enable_ssms | default(1) }}
      - InstallPPDMAgentCheckBox=1
    when: app_agent == msapp_agent_windows  

