# Example Playbok to deploy agents
- name: Deploy App Agent
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  vars:
   agent_ver: "1915"
   agent_branch: "19.15-69"  
   agent_src: /tmp
- name: Copy agent
  ansible.windows.win_copy:
    src: "{{ agent_src }}/{{ app_agent }}"
    dest: C:\Temp\