# Example Playbok to deploy agentzs
- name: Download Agents from PPDM
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variable ppdm_fqdn
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variable ppdm_new_password
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)  
 
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"   
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: Dget agents list
    include_role:
      name: get_ppdm_agents_list

  - name: Setting Agent Vars 
    vars: 
      semver_list: "{{ agents_list[0] | regex_search('([0-9]{1,2}).([0-9]{1,2})-([0-9]{1,2})', '\\1', '\\2', '\\3')}}"
      agent_major: "{{semver_list[0]}}"
      agent_minor: "{{semver_list[1]}}"
      agent_patch: "{{semver_list[2]}}"      
    set_fact:
      agents:
        agent_ver: "{{ agent_major }}{{ agent_minor }}"
        agent_branch: "{{ agent_major }}.{{ agent_minor }}-{{agent_patch}}"
        agent_release: "{{ agent_major }}.{{ agent_minor }}.0.{{agent_patch}}" 
  - local_action: 
      module: copy 
      content: "{{ agents }}"
      dest: /tmp/agents.yaml