# Example Playbok to deploy agents
- name: Deploy App Agent
  hosts: windows
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  vars:
   agent_major: 19
   agent_minor: 15
   agent_patch: 69 
   agent_ver: "{{ agent_major }}{{ agent_minor }}"
   agent_branch: "{{ agent_major }}.{{ agent_minor }}-{{agent_patch}}"
   agent_release: "{{ agent_major }}.{{ agent_minor }}.0.{{agent_patch}}" 
   agent_src: /tmp
  tasks: 
  - name: Copy agent to {{ ansible_fqdn }}
    ansible.windows.win_copy:
      src: "{{ agent_src }}/{{ app_agent }}"
      dest: C:/Temp/
  - name: Unzip Agents
    community.windows.win_unzip:
      src: "C:/Temp/{{ app_agent | basename }}"
      dest: C:/swdist
    register: unzip  
  - name: Find files in path based on regex pattern
    ansible.windows.win_find:
      paths: c:/swdist/ntx64, c:/swdist/win_x64
      patterns: "*-{{ agent_release }}.exe"
    register: find_file        
  - name: "Remove with fsagent {{ find_file.files[0].path }} on {{ ansible_fqdn }}"
    ansible.windows.win_package:
      path: "{{ find_file.files[0].path }}"
      product_id: "{{ app_agent_product_id }}"
      arguments:
      - /s 
      - /uninstall 
      - UnInstallPPDMAgent="1" 
      - UnInstallBBBWT="1"
      state: absent
    when: app_agent == fs_agent_windows
  - name: "Remove with msappagent {{ find_file.files[0].path }} on {{ ansible_fqdn }}"
    ansible.windows.win_package:
      path: "{{ find_file.files[0].path }}" 
      arguments:
      - /uninstall
      - /q 
      - UninstallAgentService="1" 
      product_id: "{{ app_agent_product_id | default('') }}"
      state: absent
    when: app_agent == msapp_agent_windows  
  - name: remove DPSAPPS directory
    ansible.windows.win_file:
      path: c:/Program Files/DPSAPPS/
      state: absent    

