# Example Playbok to deploy agents
- name: Deploy App Agent
  hosts: windows
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  vars:
   agent_ver: "1915"
   agent_branch: "19.15-69"  
   agent_src: /tmp
  tasks: 
  - name: Copy agent
    ansible.windows.win_copy:
      src: "{{ agent_src }}/{{ app_agent }}"
      dest: C:/Temp
  - name: Unzip Agents
    community.windows.win_unzip:
      src: "C:/Temp/{{ app_agent | dirname }}"
      dest: C:/swdist
      recurse: yes
      delete_archive: yes      