# Example Playbok to get PLC´s
- name: Get Protection Policies
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml

  tasks:
  - name: Checking Required Variable ppdm_fqdn
    fail: 
      msg: "We do not have ppdm_fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)  

  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"   
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: Get Protection Policies
    vars:
      filter: ''
      id: "{{ policy_id | default('') }}" 
    include_role:
      name: get_ppdm_protection_policy
  - debug: 
      msg: "{{ protection_policy | json_query('[*].{name: name,id: id}') }}"
      verbosity: 0   
    when: protection_policy is defined
  - debug: 
      msg: "{{ protection_policy }}"
      verbosity: 0   
    when: protection_policy is defined and policy_id is defined



