# Example Playbook for local AAG User
- name: Ensure Local User for SQL
  hosts: windows
  vars:
   agent_src: /tmp
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  vars:
    app_credentials_username: 'sql_service_local'
    app_credentials_name: 'bob demouser sql'
    app_credentials_password: 'Password123!'
    mssql_port: 1433        
  tasks:
  - name: "Ensure user {{ app_credentials_username }} is present"
    ansible.windows.win_user:
      name: "{{ app_credentials_username }}"
      password: "{{ app_credentials_password }}"
      state: present
      groups:
        - Users
        - Administrators

  - name: Check DB connection
    delegate_to: localhost
    community.general.mssql_script:
      login_user: "{{ ansible_user }}"
      login_password: "{{ansible_password }}"
      login_host: "{{ ansible_fqdn }}"
      login_port: "{{ mssql_port }}"
      db: master
      script: "SELECT 1"