# Example Playbok to Add DDVE to PPDM
- name: Add DDVE to PPDM
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)  
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"   
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: Get Cloud DR Account 
    include_role:
      name: get_clouddr_account
  - name: Get Clouddr Data Target
    include_role:
      name: get_clouddr_data_target  
    vars:
      jmesquery: "[? providerName=='AZURE'].id | [0]"
      id: "{{ clouddr_accounts  | json_query(jmesquery) }}"
  - name: Set CDRS Deployment
    # debug: msg="{{ clouddr_data_target  | json_query(jmesquery) }}"
    include_role:
      name: set_cdrs_deployment  
    vars:
      jmesquery: "[].id | [0]"
      id: "{{ clouddr_data_target  | json_query(jmesquery) }}"
      body:   
        cloudTargetId: "{{ id }}"
        vpcId: null
        adminPassword: "{{ ppdm_new_password }}"
        monitorPassword: "{{ ppdm_new_password }}"
        cidrBlockIp: 10.0.0.0/26
        email: Karsten.Bott@dell.com
        deleteExisting: false
        subnetId: null
        privateDeployment: false
     
  
     