# Example Playbook to configure query PPDM Server Disaster Recovery
- name: Get PPDM Assets
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"     
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  
  - name: Get PPDM Assets
    vars:
      filter: "{{ asset_filter | default('') }}"
      id: "{{ asset_id | default('')}}"
    include_role: 
      name: get_ppdm_assets
  - name: Assets Result
    debug: 
      msg: "{{ assets | json_query('[*].{name: name,id: id,type: type,protectionStatus: protectionStatus }') }}"
      verbosity: 0   
    when: assets is defined
  - name: Assets Result
    debug: 
      msg: "{{ assets }}"
      verbosity: 0   
    when: assets is defined and asset_id is defined
