# Example Playbook to configure PPDM Certificates
- name: Set PPDM License
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variables - licenseKey
    fail: 
      msg: "We do not have licenseKey !"
    when: (licenseKey is not defined) or (licenseKey|length <= 5)  
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"     
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: Get PPDM License ID
    include_role: 
      name: get_ppdm_licenses
  - name: Set PPDM License {{ licenses[0].id }}
    include_role: 
      name: set_ppdm_licenses
    vars:
      id: "{{ licenses[0].id }}"
      body: 
        key: "{{ licenseKey }}"    