# Example Playbook to configure query PPDM Server Disaster Recovery
- name: Set PPDM SDR
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"     
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  
  - name: Get PPDM Password Policy
    include_role: 
      name: get_ppdm_password_policy
  - name: Current Password Policy
    debug: 
      msg: "{{ password_policy }}"
      verbosity: 0 
  - name: merge policy body
    vars:
      my_new_policy:
        maxAge: P9999D
    set_fact:
      password_policy: "{{ password_policy | default([]) | combine(my_new_policy, recursive=True) }}"
  - debug: 
      msg: "{{ password_policy }}"
      verbosity: 0      
  - name: Set Password Policy
    include_role: 
      name: set_ppdm_password_policy
    vars:
      body:  "{{ password_policy }}"  