# Example Playbok to deploy agentzs
- name: Add DDVE to PPDM
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variable ppdm_fqdn
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variable ppdm_new_password
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)  
 
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"   
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: Download FS Agents Windows
    vars:
      agent_filename: "{{ fs_agent_windows }}"
    include_role:
      name: download_agents
  - name: Download FS Agents Linux
    vars:
      agent_filename: "{{ fs_agent_linux }}"
    include_role:
      name: download_agents      
  - name: Download MSApps Agents Windows
    vars:
      agent_filename: "{{ msapp_agent_windows }}"
    include_role:
      name: download_agents
  - name: Download Oracle Agents Linux
    vars:
      agent_filename: "{{ ora_agent_linux }}"
    include_role:
      name: download_agents
  - name: Download SAP Hana Agents Linux
    vars:
      agent_filename: "{{ dbapp_agent_linux }}"
    include_role:
      name: download_agents      
          

     