# Example Playbook to configure PPDM Certificates
- name: Get PPDM Inventory Sources
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:  
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"     
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: Get PPDM inventory-sources
    include_role: 
      name: get_ppdm_inventory-sources
    vars:
      filter: name eq "{{ ddve_fqdn }}"


  - name: Get DataDomain Storage Systems via Inventory
    include_role: 
      name: get_ppdm_inventory-sources
    vars:
      id: "{{ inventorysources[0].id }}"
      storagesystems: "true"
  - name: inventorysource Result
    debug: 
      msg: "{{ inventorysources[0] }}"
      verbosity: 0   
    when: inventorysources is defined  
    