# Example Playbok to Add DDVE to PPDM
- name: Create PPDM FLR Session
  hosts: localhost
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)  
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"   
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: cerate_flr_session
    include_role:
      name: create_flr_session
    vars:
      data: 
        copyId: 178050da-5cf8-5732-ae28-5cac05229d7b
        targetVmAssetId: 2def57c4-2278-57cf-b0a0-b0a716c1791b
        targetUser: root
        targetPassword: lola2605
        removeAgent: false
        elevateUser: false


  - name: get_flr_session
    include_role:
      name: get_flr_session
    vars: 
      id: "{{ flr_session.flrSessionId }}"
     