# Example Playbok to Add DDVE to PPDM
- name: Get PPDM Asset Settings
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)  
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"   
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: get_ppdm_asset_setting
    include_role:
      name: get_ppdm_asset_setting
  - debug: 
      msg: "{{ asset_setting }}"
      verbosity: 0     

  - name: Set Ansible Assets String 
    set_fact:
      my_asset_setting: "KUBERNETES"
    when: asset_setting.properties[0].value == ""
  - debug: 
      msg: "{{ my_asset_setting }}"
      verbosity: 0    
    when: my_asset_setting is defined
  - name: Set Ansible Assets String 
    set_fact:
      my_asset_setting: "{{ asset_setting.properties[0].value }}, KUBERNETES"
    when: asset_setting.properties[0].value != "" and "KUBERNETES" not in asset_setting.properties[0].value
  - debug: 
      msg: "{{ my_asset_setting }}"
      verbosity: 0   
    when: my_asset_setting is defined
