- name: Get PPDM Token
  uri:
    method: POST
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/login"
    body:
      username: "{{ ppdm_username }}"
      password: "{{ ppdm_password }}"
    body_format: json 
    status_code: 200
    validate_certs: false
  register: result  
  ignore_errors: '{{ ansible_check_mode }}' 
- set_fact:
    access_token: "{{ result.json.access_token }}"
