- name: GET PPDM ASSET Configuration
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/common-settings/ASSET_SETTING"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    asset_setting: "{{ result.json }}"