
- name: New PPDM Protection Policy
  vars: 
    configuration_id: "{{ new_config.id }}"
  uri:
    method: POST
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/protection-rules"
    body_format: json
    body: "{{ new_protection_rule }}"
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,201,202,403
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    protection_rule: "{{ result.json }}"
