- name: Set PPDM smtp Configuration
  uri:
    method: PUT
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/smtp/{{ id }}"
    body_format: json
    body: "{{ data }}"
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    smtp_config: "{{ result.json }}"
- debug:
    msg: "{{ smtp_config }}"
    verbosity: 0