- name: Define uri with Component ID
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/components/{{ id }}"
  when: id  | default('', true) | trim != ''
- name: Define uri without Component id
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/components"
  when: id  | default('', false) | trim == ''
- name: Get PPDM Components with status {{ condition }}
  uri:
    method: GET
    url: "{{ uri }}"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result
  until: "{{ condition }}"    
  retries: "{{ retries }}"
  delay: "{{ delay }}"
  ignore_errors: '{{ ansible_check_mode }}' 
- set_fact:
    components: "{{ result.json }}"
