- name: Get PPDM Agents List
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}/agents-list"
    headers:
      accept: "application/json, text/plain, */*"
      authorization: "Bearer {{ access_token }}" 
    status_code: 200,500
    decompress: false
    validate_certs: false
  register: result  
- set_fact:
    agents_list: "{{ result.json }}"
- debug:
    msg: "{{ agents_list }}"
    verbosity: 0    

