- name: Get PPDM Agents List
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}/agents-list"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    agents_list: "{{ result.json }}"
