- name: Get PPDM Agents List
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}/agents-list"
    headers:
      accept: application/json, text/plain
      authorization: "Bearer {{ access_token }}" 
      Xppdm-Caller: PPDM-UI   
    status_code: 200,500
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    agents_list: "{{ result}}"
- debug:
    msg: "{{ result }}"
    verbosity: 0    

