- name: Get PPDM Agents List
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}/agents-list"
    headers:
      content-type: text/html; charset=utf8
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    agents_list: "{{ result}}"
- debug:
    msg: "{{ result }}"
    verbosity: 0    

