- name: Get PPDM Configuration
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/configurations"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result  
  ignore_errors: '{{ ansible_check_mode }}' 
- set_fact:
    configuration: "{{ result.json }}"
