- name: Define uri with assets ID
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/assets/{{ id }}/copies"
- name: Rewrite uri with filter
  set_fact: 
    uri: "{{ uri }}?filter={{ filter | urlencode }}"
  when: filter  | default('', true) | trim != ''

- name: Get PPDM assetcopies with status {{ condition }}
  uri:
    method: GET
    url: "{{ uri }}"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result
  until: "{{ condition }}"    
  retries: "{{ retries }}"
  delay: "{{ delay }}"
  ignore_errors: '{{ ansible_check_mode }}' 
- set_fact:
    copies: "{{ result.json.content }}"
- debug:
    msg: "{{ copies }}"
    verbosity: 1    
