- name: Define uri with Credential ID
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/credentials/{{ id }}"
  when: id  | default('', true) | trim != ''
- name: Define uri without Credential id
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/credentials"
  when: id  | default('', false) | trim == ''
- name: Rewrite uri with filter
  set_fact: 
    uri: "{{ uri }}?filter={{ filter | string | urlencode }}" 
  when: filter   
- name: Get PPDM Credentials with filter {{ filter }}
  uri:
    method: GET
    url: "{{ uri }}"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500,503
    validate_certs: false
  register: result
  when: not ansible_check_mode 
- set_fact:
    credentials: "{{ result.json.content }}"
  when: result.json.content[0].id is defined and result.status == 200  
#- set_fact:
#    credentials: "{{ result.json }}"
#  when: result.json.consumersCount is defined and result.status == 200    
- debug:
    msg: "{{ credentials }}"     
    verbosity: 1     
  when: credentials is defined  