- name: Get PPDM Host Certificate for {{ host }}
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/certificates?host={{ host }}&port={{ port }}&type=Host"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200
    validate_certs: false
  register: result  
  ignore_errors: '{{ ansible_check_mode }}' 
- debug:
    msg: "{{ result.json }}"
    verbosity: 1
- name: return certificate
  set_fact:
    certificate: "{{ result.json }}"
