- name: Define uri with  ID
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/agent-registration-status/{{ id }}"
  when: id  | default('', true) | trim != ''
- name: Define uri without  id
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/agent-registration-status"
  when: id  | default('', false) | trim == ''
- name: Rewrite uri with filter
  set_fact: 
    uri: "{{ uri }}?filter={{ filter | string | urlencode }}"
  when: filter  | default('', true) | trim != ''

- name: Get PPDM Agent registration Status with status {{ condition }}
  uri:
    method: GET
    url: "{{ uri }}"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result
  until: "{{ condition }}"    
  retries: "{{ retries }}"
  delay: "{{ delay }}"
  when: not ansible_check_mode 
- set_fact:
    agent-registration-status: "{{ result.json.content }}"
  when: result.json.content is defined
- set_fact:
    agent-registration-status: "{{ result.json }}"
  when: id is defined and result.json is defined     
- debug:
    msg: "{{ agent-registration-status }}"
    verbosity: 0    
