- name: Define uri with activities ID
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/activities/{{ id }}"
  when: id  | default('', true) | trim != ''
- name: Define uri without activities id
  set_fact: 
    uri: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/activities"
  when: id  | default('', false) | trim == ''
- name: Rewrite uri with filter
  set_fact: 
    uri: "{{ uri }}?filter={{ filter | urlencode }}"
  when: filter  | default('', true) | trim != ''

- name: Get PPDM activities with status {{ condition }}
  uri:
    method: GET
    url: "{{ uri }}"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,500
    validate_certs: false
  register: result
  until: "{{ condition }}"    
  retries: "{{ retries }}"
  delay: "{{ delay }}"
  when: not ansible_check_mode 
- set_fact:
    activities: "{{ result.json.content }}"
- debug:
    msg: "{{ activities }}"
    verbosity: 0    
